-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        active_opacity = 0.95,
        blur = {
            passes = 2,
            popups = true,
            size = 5,
        },
        dim_inactive = false,
        inactive_opacity = 0.9,
        rounding = 5,
        shadow = {
            color = {
                colors = {"rgba(8cb1e8ff)"},
                angle = 294,
            },
            enabled = true,
            range = 2,
            render_power = 4,
            scale = 1.0,
        },
    },
    general = {
        col = {
            active_border = {
                colors = {"rgba(0703034d)"},
                angle = 15,
            },
        },
        gaps_in = 2,
        gaps_out = 2,
        snap = {
            enabled = false,
        },
    },
})

-- Keybinds
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.unbind("SUPER + R")
hl.bind("SUPER + CTRL + Return", hl.dsp.exec_cmd("rofi -show drun"))
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"))
hl.unbind("SUPER + M")
hl.bind("SUPER + bracketright", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.unbind("SUPER + CTRL + R")
hl.bind("SUPER + CTRL + R", hl.dsp.exec_cmd("hypr-reload"))
hl.unbind("SUPER + SHIFT + S")
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("wallman"))
hl.unbind("SUPER + Tab")
hl.bind("SUPER + Tab", hl.dsp.workspace.toggle_special(""))
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.window.fullscreen())
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("helium-browser"))
